// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var One = require("./One.bs.js");
var Six = require("./Six.bs.js");
var Two = require("./Two.bs.js");
var Five = require("./Five.bs.js");
var Four = require("./Four.bs.js");
var Nine = require("./Nine.bs.js");
var Eight = require("./Eight.bs.js");
var Seven = require("./Seven.bs.js");
var Three = require("./Three.bs.js");

console.log("Hello, Wofrld!");

console.log(undefined, undefined, undefined);

console.log(undefined, undefined, undefined);

console.log(undefined, undefined, undefined);

/*  Not a pure module */
